from enum import Enum
from dataclasses import dataclass
import os

# Parameters
SAVE_PATH = os.path.dirname(os.path.realpath(__file__)) + "\\Models\\"
PRETRAINING_DATASET = None
TRAINING_DATASET = None
PRETRAINED_MODEL_NAME = None
TRAINED_MODEL_NAME = None

# Constants
DUMMY_TRAIN_SIZE = 200
DUMMY_TEST_SIZE = 50

DUMMY_MICROSCOPE_PARAMETERS_NUMBER = 4
DUMMY_MAGNETIC_FIELD_SIZE = 8

POS_X = 0
POS_Y = 1
POS_A = 2
POS_B = 3
POS_THETA = 4
DUMMY_ELLIPSE_PARAMETERS_NUMBER = 5

MODE_NO_TRAINING = 0
MODE_PRETRAINING = 1
MODE_REAL_TRAINING = 2
MODE_TRAINING_FULL = 3
MODE = MODE_TRAINING_FULL


RUN_SESSION = None
EXTENSION = None

MU_PARAM_N_THETA = 0
MU_PARAM_N_PHI = 1

MU_PARAM_V0 = 2
MU_PARAM_V1 = 3
MU_PARAM_RATIO = 4
MU_PARAM_C1 = 5
MU_PARAM_C2 = 6
MU_PARAM_C3 = 7
MU_PARAM_I1 = 8
MU_PARAM_I2 = 9
MU_PARAM_I3 = 10
MU_PARAM_P1 = 11
MU_PARAM_P2 = 12
MU_PARAM_OBJ = 14
MU_PARAM_BPC = 15
MU_PARAM_BPC_X = 16
MU_PARAM_BPC_Y = 17
MU_PARAM_BPC_A = 18
MU_PARAM_BP1 = 19
MU_PARAM_BP1_X = 20
MU_PARAM_BP1_Y = 21
MU_PARAM_BP1_A = 22
MU_PARAM_BP2 = 23
MU_PARAM_BP2_X = 24
MU_PARAM_BP2_Y = 25
MU_PARAM_BP2_A = 26
MU_PARAM_APP_CO = 27
MU_PARAM_APP_CO_X = 28
MU_PARAM_APP_CO_Y = 29
MU_PARAM_APP_ST = 30
MU_PARAM_APP_ST_X = 31
MU_PARAM_APP_ST_Y = 32
MU_PARAM_APP_OB = 33
MU_PARAM_APP_OB_X = 34
MU_PARAM_APP_OB_Y = 35
MU_PARAM_APP_SA = 36
MU_PARAM_APP_SA_X = 37
MU_PARAM_APP_SA_Y = 38
MU_PARAM_SAMPLE = 39

MU_PARAM_DEF_GH_X = 40
MU_PARAM_DEF_GH_Y = 41
MU_PARAM_DEF_GHX_R = 42
MU_PARAM_DEF_GHX_Z = 43
MU_PARAM_DEF_GHY_R = 44
MU_PARAM_DEF_GHY_Z = 45

MU_PARAM_DEF_GT_X = 46
MU_PARAM_DEF_GT_Y = 47
MU_PARAM_DEF_GTX_R = 48
MU_PARAM_DEF_GTX_Z = 49
MU_PARAM_DEF_GTY_R = 50
MU_PARAM_DEF_GTY_Z = 51

MU_PARAM_DEF_GA_X = 52
MU_PARAM_DEF_GA_Y = 53

MU_PARAM_DEF_CS3_X = 54
MU_PARAM_DEF_CS3_Y = 55
MU_PARAM_DEF_CS3X_R = 56
MU_PARAM_DEF_CS3X_Z = 57
MU_PARAM_DEF_CS3Y_R = 58
MU_PARAM_DEF_CS3Y_Z = 59

MU_PARAM_DEF_CS_X = 60
MU_PARAM_DEF_CS_Y = 61
MU_PARAM_DEF_CSX_R = 62
MU_PARAM_DEF_CSX_Z = 63
MU_PARAM_DEF_CSY_R = 64
MU_PARAM_DEF_CSY_Z = 65

MU_PARAM_DEF_BH_X = 66
MU_PARAM_DEF_BH_Y = 67
MU_PARAM_DEF_BHU_X = 68
MU_PARAM_DEF_BHU_Y = 69
MU_PARAM_DEF_BHX_R = 70
MU_PARAM_DEF_BHX_Z = 71
MU_PARAM_DEF_BHY_R = 72
MU_PARAM_DEF_BHY_Z = 73

MU_PARAM_DEF_BT_X = 74
MU_PARAM_DEF_BT_Y = 75
MU_PARAM_DEF_BTU_X = 76
MU_PARAM_DEF_BTU_Y = 77
MU_PARAM_DEF_BTX_R = 78
MU_PARAM_DEF_BTX_Z = 79
MU_PARAM_DEF_BTY_R = 80
MU_PARAM_DEF_BTY_Z = 81

MU_PARAM_DEF_OS_X = 82
MU_PARAM_DEF_OS_Y = 83
MU_PARAM_DEF_OSX_R = 84
MU_PARAM_DEF_OSX_Z = 85
MU_PARAM_DEF_OSY_R = 86
MU_PARAM_DEF_OSY_Z = 87

MU_PARAM_DEF_OSP_X = 88
MU_PARAM_DEF_OSP_Y = 89

MU_PARAM_DEF_ISF_X = 90
MU_PARAM_DEF_ISF_Y = 91
MU_PARAM_DEF_ISFX_R = 92
MU_PARAM_DEF_ISFX_Z = 93
MU_PARAM_DEF_ISFY_R = 94
MU_PARAM_DEF_ISFY_Z = 95

MU_PARAM_DEF_IS_X = 96
MU_PARAM_DEF_IS_Y = 97

MU_PARAM_DEF_IA_X = 98
MU_PARAM_DEF_IA_Y = 99

MU_PARAM_DEF_PA_X = 100
MU_PARAM_DEF_PA_Y = 101

MU_PARAM_REF_PLANE = 102
MU_PARAM_LAST = 103

MU_PARAMS = range(MU_PARAM_LAST)
MU_USEFUL_PARAMS = [i for i in range(MU_PARAM_V0, MU_PARAM_OBJ+1)]
MU_USEFUL_PARAMS += [i for i in range(MU_PARAM_APP_CO, MU_PARAM_SAMPLE)]

MU_PARAM_NAMES = [
    "MU_PARAM_PHI",
    "MU_PARAM_THETA",

    "MU_PARAM_V0",
    "MU_PARAM_V1",
    "MU_PARAM_RATIO",

    "MU_PARAM_C1",
    "MU_PARAM_C2",
    "MU_PARAM_C3",

    "MU_PARAM_I1",
    "MU_PARAM_I2",
    "MU_PARAM_I3",

    "MU_PARAM_P1",
    "MU_PARAM_P2",

    "MU_PARAM_OBJ",

    "MU_PARAM_BPC",
    "MU_PARAM_BPC_X",
    "MU_PARAM_BPC_Y",
    "MU_PARAM_BPC_A",

    "MU_PARAM_BP1",
    "MU_PARAM_BP1_X",
    "MU_PARAM_BP1_Y",
    "MU_PARAM_BP1_A",

    "MU_PARAM_BP2",
    "MU_PARAM_BP2_X",
    "MU_PARAM_BP2_Y",
    "MU_PARAM_BP2_A",

    "MU_PARAM_APP_CO",
    "MU_PARAM_APP_CO_X",
    "MU_PARAM_APP_CO_Y",

    "MU_PARAM_APP_ST",
    "MU_PARAM_APP_ST_X",
    "MU_PARAM_APP_ST_Y",

    "MU_PARAM_APP_OB",
    "MU_PARAM_APP_OB_X",
    "MU_PARAM_APP_OB_Y",

    "MU_PARAM_APP_SA",
    "MU_PARAM_APP_SA_X",
    "MU_PARAM_APP_SA_Y",

    "MU_PARAM_SAMPLE",

    "MU_PARAM_DEF_GH_X",
    "MU_PARAM_DEF_GH_Y",
    "MU_PARAM_DEF_GHX_R", 
    "MU_PARAM_DEF_GHX_Z", 
    "MU_PARAM_DEF_GHY_R", 
    "MU_PARAM_DEF_GHY_Z",

    "MU_PARAM_DEF_GT_X", 
    "MU_PARAM_DEF_GT_Y", 
    "MU_PARAM_DEF_GTX_R", 
    "MU_PARAM_DEF_GTX_Z", 
    "MU_PARAM_DEF_GTY_R", 
    "MU_PARAM_DEF_GTY_Z", 
    "MU_PARAM_DEF_GA_X", 
    "MU_PARAM_DEF_GA_Y", 

    "MU_PARAM_DEF_CS3_X", 
    "MU_PARAM_DEF_CS3_Y", 
    "MU_PARAM_DEF_CS3X_R", 
    "MU_PARAM_DEF_CS3X_Z", 
    "MU_PARAM_DEF_CS3Y_R", 
    "MU_PARAM_DEF_CS3Y_Z", 
    
    "MU_PARAM_DEF_CS_X", 
    "MU_PARAM_DEF_CS_Y", 
    "MU_PARAM_DEF_CSX_R", 
    "MU_PARAM_DEF_CSX_Z",
    "MU_PARAM_DEF_CSY_R", 
    "MU_PARAM_DEF_CSY_Z", 
    
    "MU_PARAM_DEF_BH_X", 
    "MU_PARAM_DEF_BH_Y", 
    "MU_PARAM_DEF_BHU_X", 
    "MU_PARAM_DEF_BHU_Y", 
    "MU_PARAM_DEF_BHX_R", 
    "MU_PARAM_DEF_BHX_Z", 
    "MU_PARAM_DEF_BHY_R", 
    "MU_PARAM_DEF_BHY_Z", 
    
    "MU_PARAM_DEF_BT_X", 
    "MU_PARAM_DEF_BT_Y", 
    "MU_PARAM_DEF_BTU_X", 
    "MU_PARAM_DEF_BTU_Y", 
    "MU_PARAM_DEF_BTX_R", 
    "MU_PARAM_DEF_BTX_Z", 
    "MU_PARAM_DEF_BTY_R",
    "MU_PARAM_DEF_BTY_Z",
    
    "MU_PARAM_DEF_OS_X",
    "MU_PARAM_DEF_OS_Y", 
    "MU_PARAM_DEF_OSX_R",
    "MU_PARAM_DEF_OSX_Z",
    "MU_PARAM_DEF_OSY_R",
    "MU_PARAM_DEF_OSY_Z",
    
    "MU_PARAM_DEF_OSP_X",
    "MU_PARAM_DEF_OSP_Y",
    
    "MU_PARAM_DEF_ISF_X",
    "MU_PARAM_DEF_ISF_Y",
    "MU_PARAM_DEF_ISFX_R",
    "MU_PARAM_DEF_ISFX_Z",
    "MU_PARAM_DEF_ISFY_R",
    "MU_PARAM_DEF_ISFY_Z",
    
    "MU_PARAM_DEF_IS_X",
    "MU_PARAM_DEF_IS_Y",
    
    "MU_PARAM_DEF_IA_X",
    "MU_PARAM_DEF_IA_Y",
    
    "MU_PARAM_DEF_PA_X",
    "MU_PARAM_DEF_PA_Y",

    "MU_PARAM_REF_PLANE",
]

MU_PARAM_RANGES = [
    (0.00665630645849, 0.00665630645849),
    (-0.6, -0.6),

    (60000, 300000),
    "MU_PARAM_V1",
    "MU_PARAM_RATIO",

    "MU_PARAM_C1",
    "MU_PARAM_C2",
    "MU_PARAM_C3",

    "MU_PARAM_I1",
    "MU_PARAM_I2",
    "MU_PARAM_I3",

    "MU_PARAM_P1",
    "MU_PARAM_P2",

    "MU_PARAM_OBJ",

    "MU_PARAM_BPC",
    "MU_PARAM_BPC_X",
    "MU_PARAM_BPC_Y",
    "MU_PARAM_BPC_A",

    "MU_PARAM_BP1",
    "MU_PARAM_BP1_X",
    "MU_PARAM_BP1_Y",
    "MU_PARAM_BP1_A",

    "MU_PARAM_BP2",
    "MU_PARAM_BP2_X",
    "MU_PARAM_BP2_Y",
    "MU_PARAM_BP2_A",

    "MU_PARAM_APP_CO",
    "MU_PARAM_APP_CO_X",
    "MU_PARAM_APP_CO_Y",

    "MU_PARAM_APP_ST",
    "MU_PARAM_APP_ST_X",
    "MU_PARAM_APP_ST_Y",

    "MU_PARAM_APP_OB",
    "MU_PARAM_APP_OB_X",
    "MU_PARAM_APP_OB_Y",

    "MU_PARAM_APP_SA",
    "MU_PARAM_APP_SA_X",
    "MU_PARAM_APP_SA_Y",

    "MU_PARAM_SAMPLE",

    "MU_PARAM_DEF_GH_X",
    "MU_PARAM_DEF_GH_Y",
    "MU_PARAM_DEF_GHX_R",
    "MU_PARAM_DEF_GHX_Z",
    "MU_PARAM_DEF_GHY_R",
    "MU_PARAM_DEF_GHY_Z",

    "MU_PARAM_DEF_GT_X",
    "MU_PARAM_DEF_GT_Y",
    "MU_PARAM_DEF_GTX_R",
    "MU_PARAM_DEF_GTX_Z",
    "MU_PARAM_DEF_GTY_R",
    "MU_PARAM_DEF_GTY_Z",
    "MU_PARAM_DEF_GA_X",
    "MU_PARAM_DEF_GA_Y",

    "MU_PARAM_DEF_CS3_X",
    "MU_PARAM_DEF_CS3_Y",
    "MU_PARAM_DEF_CS3X_R",
    "MU_PARAM_DEF_CS3X_Z",
    "MU_PARAM_DEF_CS3Y_R",
    "MU_PARAM_DEF_CS3Y_Z",

    "MU_PARAM_DEF_CS_X",
    "MU_PARAM_DEF_CS_Y",
    "MU_PARAM_DEF_CSX_R",
    "MU_PARAM_DEF_CSX_Z",
    "MU_PARAM_DEF_CSY_R",
    "MU_PARAM_DEF_CSY_Z",

    "MU_PARAM_DEF_BH_X",
    "MU_PARAM_DEF_BH_Y",
    "MU_PARAM_DEF_BHU_X",
    "MU_PARAM_DEF_BHU_Y",
    "MU_PARAM_DEF_BHX_R",
    "MU_PARAM_DEF_BHX_Z",
    "MU_PARAM_DEF_BHY_R",
    "MU_PARAM_DEF_BHY_Z",

    "MU_PARAM_DEF_BT_X",
    "MU_PARAM_DEF_BT_Y",
    "MU_PARAM_DEF_BTU_X",
    "MU_PARAM_DEF_BTU_Y",
    "MU_PARAM_DEF_BTX_R",
    "MU_PARAM_DEF_BTX_Z",
    "MU_PARAM_DEF_BTY_R",
    "MU_PARAM_DEF_BTY_Z",

    "MU_PARAM_DEF_OS_X",
    "MU_PARAM_DEF_OS_Y",
    "MU_PARAM_DEF_OSX_R",
    "MU_PARAM_DEF_OSX_Z",
    "MU_PARAM_DEF_OSY_R",
    "MU_PARAM_DEF_OSY_Z",

    "MU_PARAM_DEF_OSP_X",
    "MU_PARAM_DEF_OSP_Y",

    "MU_PARAM_DEF_ISF_X",
    "MU_PARAM_DEF_ISF_Y",
    "MU_PARAM_DEF_ISFX_R",
    "MU_PARAM_DEF_ISFX_Z",
    "MU_PARAM_DEF_ISFY_R",
    "MU_PARAM_DEF_ISFY_Z",

    "MU_PARAM_DEF_IS_X",
    "MU_PARAM_DEF_IS_Y",

    "MU_PARAM_DEF_IA_X",
    "MU_PARAM_DEF_IA_Y",

    "MU_PARAM_DEF_PA_X",
    "MU_PARAM_DEF_PA_Y",

    "MU_PARAM_REF_PLANE",
]


def run_session():
    return RUN_SESSION


def current_extension():
    return EXTENSION


def set_run_session(extension, filename=SAVE_PATH + "run_counter.dat"):
    global EXTENSION
    EXTENSION = extension
    with open(filename, "a+") as f:
        f.seek(0)
        global RUN_SESSION
        RUN_SESSION = int(f.read() or 0) + 1
        f.seek(0)
        f.truncate()
        f.write(str(RUN_SESSION))

